name = "Heat"
uuid = "f84b640a-e15b-4457-b8f5-f363600232bd"
authors = ["CSDMS, Deltares and contributors"]
version = "0.1.0"

[deps]
BasicModelInterface = "59605e27-edc0-445a-b93d-c09a3a50b330"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
BasicModelInterface = "0.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
